FL_alpha: 1.3177083333333333
FL_gamma: 2
batch_size: 4
bn_momentum: 0.5
bnm_decay: 0.5
decay_step: 300000.0
description: Instance segmentation of leaves - DGCNN module - MinMax normalization
feature_space_dim: 512
feed_is_focal: false
feed_leaf_part: false
hparams:
  FL_alpha: 1.3177083333333333
  FL_gamma: 2
  batch_size: 4
  bn_momentum: 0.5
  bnm_decay: 0.5
  decay_step: 300000.0
  description: Instance segmentation of leaves - DGCNN module - MinMax normalization
  feature_space_dim: 512
  feed_is_focal: false
  feed_leaf_part: false
  input_channels: 0
  lc_count: 256
  leaf_space_threshold: 5
  lr: 0.001
  lr_decay: 0.5
  train_data: /space/ariyanzarei/sorghum_segmentation/dataset/2022-03-10/sorghum__labeled_train.hdf5
  use_deep: true
  use_fine_leaf_index: false
  use_xyz: true
  val_data: /space/ariyanzarei/sorghum_segmentation/dataset/2022-03-10/sorghum__labeled_validation.hdf5
  weight_decay: 0.0
input_channels: 0
lc_count: 256
leaf_space_threshold: 5
lr: 0.001
lr_decay: 0.5
train_data: /space/ariyanzarei/sorghum_segmentation/dataset/2022-03-10/sorghum__labeled_train.hdf5
use_deep: true
use_fine_leaf_index: false
use_xyz: true
val_data: /space/ariyanzarei/sorghum_segmentation/dataset/2022-03-10/sorghum__labeled_validation.hdf5
weight_decay: 0.0
