batch_size: 4
bn_momentum: 0.5
bnm_decay: 0.5
decay_step: 300000
description: Semantic Segmentation (Soil, Focal and Non-focal plant) - DGCNN Module
  - MinMax normalization - Normals added - Noise added - dataset format changed -
  Instance will be only on focal plant
epochs: 20
feature_space_dim: 512
gpus: &id001
- 1
hparams:
  batch_size: 4
  bn_momentum: 0.5
  bnm_decay: 0.5
  decay_step: 300000
  description: Semantic Segmentation (Soil, Focal and Non-focal plant) - DGCNN Module
    - MinMax normalization - Normals added - Noise added - dataset format changed
    - Instance will be only on focal plant
  epochs: 20
  feature_space_dim: 512
  gpus: *id001
  leaf_space_threshold: 5
  lr: 0.001
  lr_decay: 0.5
  normalization: min-max
  train_data: /space/ariyanzarei/sorghum_segmentation/dataset/synthetic/2022-09-29/h5_new/semantic_segmentation_train.hdf5
  use_normals: true
  val_data: /space/ariyanzarei/sorghum_segmentation/dataset/synthetic/2022-09-29/h5_new/semantic_segmentation_validation.hdf5
  weight_decay: 0.0
leaf_space_threshold: 5
lr: 0.001
lr_decay: 0.5
normalization: min-max
train_data: /space/ariyanzarei/sorghum_segmentation/dataset/synthetic/2022-09-29/h5_new/semantic_segmentation_train.hdf5
use_normals: true
val_data: /space/ariyanzarei/sorghum_segmentation/dataset/synthetic/2022-09-29/h5_new/semantic_segmentation_validation.hdf5
weight_decay: 0.0
