FL_alpha: 1.3177083333333333
FL_gamma: 2
batch_size: 4
bn_momentum: 0.5
bnm_decay: 0.5
decay_step: 300000.0
description: Leaf Classification (Single / Paired Leaf) - DGCNN Module - MinMax normalization
feature_space_dim: 512
hparams:
  FL_alpha: 1.3177083333333333
  FL_gamma: 2
  batch_size: 4
  bn_momentum: 0.5
  bnm_decay: 0.5
  decay_step: 300000.0
  description: Leaf Classification (Single / Paired Leaf) - DGCNN Module - MinMax
    normalization
  feature_space_dim: 512
  input_channels: 0
  lc_count: 256
  lr: 0.001
  lr_decay: 0.5
  train_data: /space/murph186/sorghum_segmentation/dataset/2022-03-10_leaf_b/sorghum_leaf__labeled_train.hdf5
  use_deep: true
  use_fine_leaf_index: false
  use_xyz: true
  val_data: /space/murph186/sorghum_segmentation/dataset/2022-03-10_leaf_b/sorghum_leaf__labeled_validation.hdf5
  weight_decay: 0.0
input_channels: 0
lc_count: 256
lr: 0.001
lr_decay: 0.5
train_data: /space/murph186/sorghum_segmentation/dataset/2022-03-10_leaf_b/sorghum_leaf__labeled_train.hdf5
use_deep: true
use_fine_leaf_index: false
use_xyz: true
val_data: /space/murph186/sorghum_segmentation/dataset/2022-03-10_leaf_b/sorghum_leaf__labeled_validation.hdf5
weight_decay: 0.0
